import type { Metadata } from "next";

import "./globals.css";

export const metadata: Metadata = {
    title: "Image Gallery",
    description: "images generated by pexels",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <head>
                <link
                    href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined&display=optional"
                    rel="stylesheet"
                />
            </head>
            <body
                className="flex flex-col min-w-dvw min-h-dvh pt-5
             "
            >
                {children}
            </body>
        </html>
    );
}
